### ISSUE TITLE
Does overscroll-behavior apply to iframe?

### ISSUE THREAD

**Issue by hax** [WICG/overscroll-behavior#31]
It seems both chrome and ff not support `overscroll-behavior: none/contain` on iframe element. Does it a implementation bug or spec limitation?

**Comment by hax** [comment]
I also tried apply style on the document in iframe.
```css
html {overscroll-behavior: none;}
```
Not work.

---

```css
html {
	overflow: hidden;
}
body {
	height: 100vh;
	margin: 0;
	overflow: auto;
	overscroll-behavior: none;
}
```

Work for FF, but not Chrome.
